<template>
  <div class="home">
    <img
      id="logoId"
      class="logo"
      alt="بسم الله الرحمن رحیم"
      src="../assets/img/Allah.png"
    />
    <form class="form-wrapper">
      <input v-model="input_value" type="text" placeholder="اسم سوره ..." />
      <button type="button" @click="search">
        <span class="button-icon">&#128269;</span>
        <span class="button-text">جستجو</span>
      </button>
    </form>
    <p class="popularity-title">«سوره های پربازدید»</p>
    <div class="popularity-box">
      <div class="popularity-div" v-for="n in 4" :key="n">
        <p class="popularity-name">سوره : <span>mohsen</span></p>
        <p class="popularity-number">شماره : <span>2</span></p>
        <p class="popularity-part">جزء : <span>[3, 4]</span></p>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Swal from "sweetalert2";
import { defineComponent } from "vue";


export default defineComponent({
  name: "Home",
  components: {},
  data() {
    return {
      input_x: 0,
      input_value: "",
      quran_name: [
        {
          id: 1,
          ar_name: "الحمد",
          pa_name: "ستایش",
          ayats: 6,
          part: [1],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 2,
          ar_name: "البقرة",
          pa_name: "گاو",
          ayats: 286,
          part: [1, 2, 3],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 3,
          ar_name: "آل عمران",
          pa_name: "آل عمران",
          ayats: 199,
          part: [3, 4],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 4,
          ar_name: "النساء",
          pa_name: "زنان",
          ayats: 175,
          part: [4, 5, 6],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 5,
          ar_name: "المائدة",
          pa_name: "میز",
          ayats: 119,
          part: [6, 7],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 6,
          ar_name: "الأنعام",
          pa_name: "گاو",
          ayats: 164,
          part: [7, 8],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 7,
          ar_name: "الأعراف",
          pa_name: "آداب و رسوم",
          ayats: 205,
          part: [8, 9],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 8,
          ar_name: "الأنفال",
          pa_name: "انفال",
          ayats: 74,
          part: [9, 10],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 9,
          ar_name: "التوبة",
          pa_name: "توبه",
          ayats: 128,
          part: [10, 11],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 10,
          ar_name: "يونس",
          pa_name: "یونس",
          ayats: 108,
          part: [11],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 11,
          ar_name: "هود",
          pa_name: "هود",
          ayats: 122,
          part: [11, 12],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 12,
          ar_name: "يوسف",
          pa_name: "يوسف",
          ayats: 110,
          part: [12, 13],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 13,
          ar_name: "الرعد",
          pa_name: "رعد و برق",
          ayats: 42,
          part: [13],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 14,
          ar_name: "إبراهيم",
          pa_name: "ابراهیم",
          ayats: 51,
          part: [13],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 15,
          ar_name: "الحجر",
          pa_name: "سنگ",
          ayats: 98,
          part: [14],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 16,
          ar_name: "النحل",
          pa_name: "زنبورها",
          ayats: 127,
          part: [14],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 17,
          ar_name: "الإسراء",
          pa_name: "ایسرا",
          ayats: 110,
          part: [15],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 18,
          ar_name: "الكهف",
          pa_name: "غار",
          ayats: 109,
          part: [15, 16],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 19,
          ar_name: "مريم",
          pa_name: "مريم",
          ayats: 97,
          part: [16],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 20,
          ar_name: "طه",
          pa_name: "طه",
          ayats: 134,
          part: [16],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 21,
          ar_name: "الأنبياء",
          pa_name: "پیامبران",
          ayats: 111,
          part: [17],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 22,
          ar_name: "الحج",
          pa_name: "زیارت",
          ayats: 77,
          part: [17],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 23,
          ar_name: "المؤمنون",
          pa_name: "مومنان",
          ayats: 117,
          part: [18],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 24,
          ar_name: "النور",
          pa_name: "روشنایی",
          ayats: 63,
          part: [18],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 25,
          ar_name: "الفرقان",
          pa_name: "فرقان",
          ayats: 76,
          part: [18, 19],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 26,
          ar_name: "الشعراء",
          pa_name: "شاعران",
          ayats: 226,
          part: [19],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 27,
          ar_name: "النمل",
          pa_name: "مورچه ها",
          ayats: 92,
          part: [19, 20],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 28,
          ar_name: "القصص",
          pa_name: "داستان ها",
          ayats: 87,
          part: [20],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 29,
          ar_name: "العنكبوت",
          pa_name: "عنکبوت",
          ayats: 68,
          part: [20, 21],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 30,
          ar_name: "الروم",
          pa_name: "رم",
          ayats: 59,
          part: [21],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 31,
          ar_name: "لقمان",
          pa_name: "لقمان",
          ayats: 33,
          part: [21],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 32,
          ar_name: "السجدة",
          pa_name: "سجده",
          ayats: 29,
          part: [21],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 33,
          ar_name: "الأحزاب",
          pa_name: "مهمانی",
          ayats: 72,
          part: [21, 22],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 34,
          ar_name: "سبأ",
          pa_name: "شبا",
          ayats: 53,
          part: [22],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 35,
          ar_name: "فاطر",
          pa_name: "خالق",
          ayats: 44,
          part: [22],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 36,
          ar_name: "يس",
          pa_name: "یس",
          ayats: 82,
          part: [22, 23],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 37,
          ar_name: "الصافات",
          pa_name: "صفات",
          ayats: 181,
          part: [23],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 38,
          ar_name: "ص",
          pa_name: "ص",
          ayats: 87,
          part: [23],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 39,
          ar_name: "الزمر",
          pa_name: "گروه ها",
          ayats: 74,
          part: [23, 24],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 40,
          ar_name: "غافر",
          pa_name: "بخشنده",
          ayats: 84,
          part: [24],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 41,
          ar_name: "فصلت",
          pa_name: "فصلت",
          ayats: 53,
          part: [24, 25],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 42,
          ar_name: "الشورى",
          pa_name: "شورا",
          ayats: 52,
          part: [25],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 43,
          ar_name: "الزخرف",
          pa_name: "تزیین",
          ayats: 88,
          part: [25],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 44,
          ar_name: "الدخان",
          pa_name: "دود",
          ayats: 58,
          part: [25],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 45,
          ar_name: "الجاثية",
          pa_name: "زانو زدن",
          ayats: 36,
          part: [25],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 46,
          ar_name: "الأحقاف",
          pa_name: "الاحقاف",
          ayats: 34,
          part: [26],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 47,
          ar_name: "محمد",
          pa_name: "محمد",
          ayats: 37,
          part: [26],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 48,
          ar_name: "الفتح",
          pa_name: "تسخیر",
          ayats: 28,
          part: [26],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 49,
          ar_name: "الحجرات",
          pa_name: "گنجه ها",
          ayats: 17,
          part: [26],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 50,
          ar_name: "ق",
          pa_name: "ق",
          ayats: 44,
          part: [26],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 51,
          ar_name: "الذاريات",
          pa_name: "اتمیک",
          ayats: 59,
          part: [26, 27],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 52,
          ar_name: "الطور",
          pa_name: "فاز",
          ayats: 48,
          part: [27],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 53,
          ar_name: "النجم",
          pa_name: "ستاره",
          ayats: 61,
          part: [27],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 54,
          ar_name: "القمر",
          pa_name: "ماه",
          ayats: 54,
          part: [27],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 55,
          ar_name: "الرحمن",
          pa_name: "رحیم",
          ayats: 77,
          part: [27],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 56,
          ar_name: "الواقعة",
          pa_name: "حادثه",
          ayats: 95,
          part: [27],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 57,
          ar_name: "الحديد",
          pa_name: "اهن",
          ayats: 28,
          part: [27],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 58,
          ar_name: "المجادلة",
          pa_name: "استدلال",
          ayats: 21,
          part: [28],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 59,
          ar_name: "الحشر",
          pa_name: "گرفتگی",
          ayats: 23,
          part: [28],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 60,
          ar_name: "الممتحنة",
          pa_name: "مورد آزمایش",
          ayats: 12,
          part: [28],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 61,
          ar_name: "الصف",
          pa_name: "خط",
          ayats: 13,
          part: [28],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 62,
          ar_name: "الجمعة",
          pa_name: "جمعه",
          ayats: 10,
          part: [28],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 63,
          ar_name: "المنافقون",
          pa_name: "منافقین",
          ayats: 10,
          part: [28],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 64,
          ar_name: "التغبن",
          pa_name: "آلتبگن",
          ayats: 17,
          part: [28],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 65,
          ar_name: "الطلاق",
          pa_name: "طلاق",
          ayats: 11,
          part: [28],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 66,
          ar_name: "التحريم",
          pa_name: "ممنوعیت",
          ayats: 11,
          part: [28],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 67,
          ar_name: "الملك",
          pa_name: "پادشاه",
          ayats: 29,
          part: [29],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 68,
          ar_name: "القلم",
          pa_name: "قلم",
          ayats: 51,
          part: [29],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 69,
          ar_name: "الحاقة",
          pa_name: "ضمیمه",
          ayats: 51,
          part: [29],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 70,
          ar_name: "المعارج",
          pa_name: "ماریج",
          ayats: 43,
          part: [29],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 71,
          ar_name: "نوح",
          pa_name: "نوح",
          ayats: 27,
          part: [29],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 72,
          ar_name: "الجن",
          pa_name: "جن",
          ayats: 27,
          part: [29],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 73,
          ar_name: "المزمل",
          pa_name: "المزمل",
          ayats: 19,
          part: [29],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 74,
          ar_name: "المدثر",
          pa_name: "آمما",
          ayats: 55,
          part: [29],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 75,
          ar_name: "القيامة",
          pa_name: "رستاخیز",
          ayats: 39,
          part: [29],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 76,
          ar_name: "الإنسان",
          pa_name: "انسان",
          ayats: 30,
          part: [29],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 77,
          ar_name: "المرسلات",
          pa_name: "مرسلات",
          ayats: 49,
          part: [29],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 78,
          ar_name: "النبأ",
          pa_name: "اخبار",
          ayats: 39,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 79,
          ar_name: "النازعات",
          pa_name: "اختلافات",
          ayats: 45,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 80,
          ar_name: "عبس",
          pa_name: "اخم",
          ayats: 41,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 81,
          ar_name: "التكوير",
          pa_name: "گلوله سازی",
          ayats: 28,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 82,
          ar_name: "الإنفطار",
          pa_name: "صبحانه",
          ayats: 18,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 83,
          ar_name: "المطففين",
          pa_name: "مطیففین",
          ayats: 35,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 84,
          ar_name: "الانشقاق",
          pa_name: "شقاق",
          ayats: 24,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 85,
          ar_name: "البروج",
          pa_name: "زودیاک",
          ayats: 21,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 86,
          ar_name: "الطارق",
          pa_name: "کوبنده",
          ayats: 16,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 87,
          ar_name: "الأعلى",
          pa_name: "بالا",
          ayats: 18,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 88,
          ar_name: "الغاشية",
          pa_name: "غاشیه",
          ayats: 25,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 89,
          ar_name: "الفجر",
          pa_name: "طلوع",
          ayats: 29,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 90,
          ar_name: "البلد",
          pa_name: "کشور",
          ayats: 19,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 91,
          ar_name: "الشمس",
          pa_name: "خورشید",
          ayats: 14,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 92,
          ar_name: "الليل",
          pa_name: "شب",
          ayats: 20,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 93,
          ar_name: "الضحى",
          pa_name: "صبح",
          ayats: 10,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 94,
          ar_name: "الانشراح",
          pa_name: "اینشیره",
          ayats: 7,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 95,
          ar_name: "التين",
          pa_name: "شکل",
          ayats: 7,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 96,
          ar_name: "العلق",
          pa_name: "زالو",
          ayats: 18,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 97,
          ar_name: "القدر",
          pa_name: "سرنوشت",
          ayats: 4,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 98,
          ar_name: "البينة",
          pa_name: "شواهد",
          ayats: 7,
          part: [30],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 99,
          ar_name: "الزلزال",
          pa_name: "زلزله",
          ayats: 7,
          part: [30],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 100,
          ar_name: "العاديات",
          pa_name: "عادی",
          ayats: 10,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 101,
          ar_name: "القارعة",
          pa_name: "کوبنده",
          ayats: 10,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 102,
          ar_name: "التكاثر",
          pa_name: "تولید مثل",
          ayats: 7,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 103,
          ar_name: "العصر",
          pa_name: "سن",
          ayats: 2,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 104,
          ar_name: "الهمزة",
          pa_name: "حمزه",
          ayats: 8,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 105,
          ar_name: "الفيل",
          pa_name: "فيل",
          ayats: 4,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 106,
          ar_name: "قريش",
          pa_name: "قریش",
          ayats: 3,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 107,
          ar_name: "الماعون",
          pa_name: "ریم",
          ayats: 6,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 108,
          ar_name: "الكوثر",
          pa_name: "كوثر",
          ayats: 2,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 109,
          ar_name: "الكافرون",
          pa_name: "بی ایمانان",
          ayats: 5,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 110,
          ar_name: "النصر",
          pa_name: "پیروزی",
          ayats: 2,
          part: [30],
          mkORmd: false,
          popularity: 1,
        },
        {
          id: 111,
          ar_name: "لهب",
          pa_name: "شعله",
          ayats: 4,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 112,
          ar_name: "الإخلاص",
          pa_name: "اخلاص",
          ayats: 3,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 113,
          ar_name: "الفلق",
          pa_name: "فلق",
          ayats: 4,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
        {
          id: 114,
          ar_name: "الناس",
          pa_name: "مردم",
          ayats: 5,
          part: [30],
          mkORmd: true,
          popularity: 1,
        },
      ],
    };
  },
  methods: {
    search() {
      if (this.input_value == "") {
        Swal.fire({
          icon: "warning",
          iconColor:"red",
          title: "خطا!",
          text: "لطفا اسم سوره را وارد کنید",
          showCloseButton: true,
          showConfirmButton: false,
          background:"#999",
        });
      } else {
        for (let i = 0; i < 114; i++) {
          if (
            this.input_value == this.quran_name[i].ar_name ||
            this.input_value == this.quran_name[i].pa_name
          ) {
            this.input_x = 1;
            this.$router.push({
              name: "Show",
              params: { id: this.quran_name[i].id, name: this.quran_name[i].ar_name },
            });
          }
        }
        if (this.input_x == 0) {
          Swal.fire({
            icon: "error",
            title: "خطا!",
            text: "اسم مورد نظر یافت نشد",
            showCloseButton: true,
            showConfirmButton: false,
          });
        }
      }
    },
    moveLog() {
      const logoImg = document.querySelector("#logoId") as HTMLDivElement;
      logoImg.addEventListener("mousemove", (event) => {
        let x = window.innerWidth / 10;
        let y = window.innerHeight / 10;
        let x1 = x - event.pageX;
        let y1 = y - event.pageY;
        logoImg.style.transform = `translate(${x1 / 20}px,${y1 / 20}px)`;
      });
      logoImg.addEventListener("mouseleave", () => {
        logoImg.style.transform = `translate(0px,0px)`;
        logoImg.style.transition = "all 1s ease";
      });
      logoImg.addEventListener("mouseenter", () => {
        logoImg.style.transition = "none";
      });
    },
  },
  mounted: function() {
    this.moveLog();
  },
});
</script>
<style lang="scss">
@import "../assets/scss/__home.scss";
</style>
